---
- name: Create admin user
  ansible.builtin.user:
    name: '{{ admin_username }}'
    shell: '{{ admin_shell }}'
    state: present

- name: Create ssh directory
  ansible.builtin.file:
    path: '/home/{{ admin_username }}/.ssh'
    state: directory
    owner: '{{ admin_username }}'
    group: '{{ admin_username }}'
    mode: 0700

- name: Copy ssh key
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    dest: '/home/{{ admin_username}}/.ssh/.'
    owner: '{{ admin_username }}'
    group: '{{ admin_username }}'
    mode: 0600
    remote_src: true

- name: Install sudo
  ansible.builtin.apt:
    name: [ 'sudo' ]
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure sudoers
  community.general.sudoers:
    name: admin_nopass
    user: admin
    commands: [ 'ALL' ]
    nopassword: true
